# Generated by Django 3.2.10 on 2021-12-18 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FriendshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('accept', models.BooleanField(default=False, verbose_name='Принять запрос')),
            ],
            options={
                'verbose_name': 'Запрос дружбы',
                'verbose_name_plural': 'Запросы дружбы',
            },
        ),
    ]
