# Generated by Django 3.2.10 on 2021-12-18 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('is_private', models.BooleanField(default=False, verbose_name='Сделать приватным')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Фото-альбом',
                'verbose_name_plural': 'Фото-альбомы',
                'unique_together': {('user', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='%Y/%m/', verbose_name='Фото')),
                ('desc', models.TextField(blank=True, max_length=2000, verbose_name='Описание')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.photoalbum', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ['date_added'],
            },
        ),
    ]
